apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:

  replicas: 5
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: piyush540/chatbot:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"